### ISSUE TITLE
segfault in ipmi_sel_set_time

### ISSUE THREAD

**Issue by dgloe-hpe** [ipmitool/ipmitool#362]
I'm seeing a segfault when trying to set the time:

```
ncn-m001:~ # ipmitool -I lanplus -U XXXXXX -P XXXXXX -H XXXXXX sel time set "9/14/2022 06:53:00"
Segmentation fault (core dumped)
ncn-m001:~ # gdb -c ./core /usr/bin/ipmitool
...
(gdb) bt
#0  htoipmi32 (ipmi=0x0, h=1663149600) at ../include/ipmitool/helper.h:203
#1  ipmi_sel_set_time (time_string=0x7ffd80a3969d "9/14/2022 06:53:00",
    intf=0x5598bb549ba0 <ipmi_lanplus_intf>) at ipmi_sel.c:2790
#2  ipmi_sel_main (intf=0x5598bb549ba0 <ipmi_lanplus_intf>, argc=<optimized out>, argv=0x7ffd80a38138)
    at ipmi_sel.c:3128
#3  0x00005598bb2b3e64 in ipmi_main (argc=<optimized out>, argv=<optimized out>,
    cmdlist=cmdlist@entry=0x5598bb53d5e0 <ipmitool_cmd_list>, intflist=intflist@entry=0x0)
    at ipmi_main.c:1017
#4  0x00005598bb274a32 in main (argc=<optimized out>, argv=<optimized out>) at ipmitool.c:135

ncn-m001:~ # ipmitool -V
ipmitool version 1.8.18
```

**Comment by AlexanderAmelkin** [comment]
Pleas do not report anything about 1.8.18. It is too old. There is even [1.8.19](https://github.com/ipmitool/ipmitool/releases/tag/IPMITOOL_1_8_19) already. This has probably been fixed ages ago.
